// Auto generated, do not modify manually
export type CompleteWeekInfo = [number, number, number[]];
export type PartialWeekInfo = [number, number?, number[]?];
export type RegionData = Record<string, PartialWeekInfo>;

export const worldDefaults: CompleteWeekInfo = [1, 1, [6, 7]];
export const regionData: RegionData = {
    AD: [1, 4],
    AF: [6, 1, [4, 5]],
    AG: [7],
    AS: [7],
    AT: [1, 4],
    AX: [1, 4],
    BD: [7],
    BE: [1, 4],
    BG: [1, 4],
    BH: [6, 1, [5, 6]],
    BR: [7],
    BS: [7],
    BT: [7],
    BW: [7],
    BZ: [7],
    CA: [7],
    CH: [1, 4],
    CO: [7],
    CZ: [1, 4],
    DE: [1, 4],
    DJ: [6],
    DK: [1, 4],
    DM: [7],
    DO: [7],
    DZ: [6, 1, [5, 6]],
    EE: [1, 4],
    EG: [6, 1, [5, 6]],
    ES: [1, 4],
    ET: [7],
    FI: [1, 4],
    FJ: [1, 4],
    FO: [1, 4],
    FR: [1, 4],
    GB: [1, 4],
    GF: [1, 4],
    GG: [1, 4],
    GI: [1, 4],
    GP: [1, 4],
    GR: [1, 4],
    GT: [7],
    GU: [7],
    HK: [7],
    HN: [7],
    HU: [1, 4],
    ID: [7],
    IE: [1, 4],
    IL: [7, 1, [5, 6]],
    IM: [1, 4],
    IN: [7, 1, [7]],
    IQ: [6, 1, [5, 6]],
    IR: [6, 1, [5]],
    IS: [1, 4],
    IT: [1, 4],
    JE: [1, 4],
    JM: [7],
    JO: [6, 1, [5, 6]],
    JP: [7],
    KE: [7],
    KH: [7],
    KR: [7],
    KW: [6, 1, [5, 6]],
    LA: [7],
    LI: [1, 4],
    LT: [1, 4],
    LU: [1, 4],
    LY: [6, 1, [5, 6]],
    MC: [1, 4],
    MH: [7],
    MM: [7],
    MO: [7],
    MQ: [1, 4],
    MT: [7],
    MV: [5],
    MX: [7],
    MZ: [7],
    NI: [7],
    NL: [1, 4],
    NO: [1, 4],
    NP: [7],
    OM: [6, 1, [5, 6]],
    PA: [7],
    PE: [7],
    PH: [7],
    PK: [7],
    PL: [1, 4],
    PR: [7],
    PT: [7, 4],
    PY: [7],
    QA: [6, 1, [5, 6]],
    RE: [1, 4],
    RU: [1, 4],
    SA: [7, 1, [5, 6]],
    SD: [6, 1, [5, 6]],
    SE: [1, 4],
    SG: [7],
    SJ: [1, 4],
    SK: [1, 4],
    SM: [1, 4],
    SV: [7],
    SY: [6, 1, [5, 6]],
    TH: [7],
    TT: [7],
    TW: [7],
    UG: [1, 1, [7]],
    UM: [7],
    US: [7],
    VA: [1, 4],
    VE: [7],
    VI: [7],
    WS: [7],
    YE: [7, 1, [5, 6]],
    ZA: [7],
    ZW: [7],
};
